name: vienna.css
url: viennacss.github.io
description: Vienna's CSS meetup and user group

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
